### ISSUE TITLE
Question about number of sites for CHAT manual NeuroPsych 5.4.1 

### ISSUE THREAD

**Issue by JLArnold** [nsrr/chat-documentation#21]
https://www.sleepdata.org/datasets/chat/pages/manuals/neuropsychology/5-04-np-study-sites.md
Here is a general question about CHAT for this manual and the PSG Reading Center manual: there were four clinical sites at the start of CHAT, in order to meet quota of subjects three more sites were added to CHAT. Should this information be added to the manuals? Or some place on the NSRR site?
CHAT did start with just 4 clinical sites [10=CHOP, 20=CINN, 30=CLE, 40=LVL] then added three more sites [50=SLU [St.Louis], 60=NY, and 70=Boston], total of 7 sites for CHAT.  Then at some point they dropped LVL site 40 [Louisville].
![image](https://cloud.githubusercontent.com/assets/16805718/12517063/e032ac26-c0fe-11e5-8e2c-a615533ff196.png)

![image](https://cloud.githubusercontent.com/assets/16805718/12517085/fc17e79e-c0fe-11e5-9e66-defab647d587.png)

**Comment by StephanieMarvin** [comment]
did not add additional sites because these are related to study design, study was designed with 4 sites originally, others added later
