### ISSUE TITLE
Figure to show ECG electrode placement should had 3 electrodes CHAT ReadingCenter manual 6.5.10 Suggested Order of PSG hook-up

### ISSUE THREAD

**Issue by JLArnold** [nsrr/chat-documentation#29]
https://www.sleepdata.org/datasets/chat/pages/manuals/polysomnography-reading-center/6-05-10-suggested-order-of-psg-hook-up.md

CHAT manual PSG Reading Center 6.5.10 Suggested Order of PSG Hook-up  ECG electrodes figure only shows placement of two ECG electrodes, this study used 3 electrodes for ECG [this is the figure from the CHAT MOP but it should show the placement of the three ECG electrodes] the third electrode should be blow the left clavicle

![image](https://cloud.githubusercontent.com/assets/16805718/12586571/d260a120-c41e-11e5-8d8b-da9f94d685c4.png)

**Comment by mrueschman** [comment]
Directly from MOP, won't correct at this point. Closing issue.
