### ISSUE TITLE
Electrode Placement Quick Reference should have name by each arrow CHAT PSG ReadingCenter 6.5.10 Suggested Order of PSG hook-up

### ISSUE THREAD

**Issue by JLArnold** [nsrr/chat-documentation#30]
https://www.sleepdata.org/datasets/chat/pages/manuals/polysomnography-reading-center/6-05-10-suggested-order-of-psg-hook-up.md

CHAT manual PSG Reading Center 6.5.10 Suggested Order of PSG Hook-up, Electrode placement Quick Reference has arrows but not the name of the electrodes, the MOP has this same figure without electrode names by the arrows.  Example of same figure with electrode names is in the MrOS visit 2 MOP PDF on NSRR using the electrode names from the AASM 2007 rules.

![image](https://cloud.githubusercontent.com/assets/16805718/12586760/907c1220-c41f-11e5-8099-e838c747341d.png)

![image](https://cloud.githubusercontent.com/assets/16805718/12586774/9d2bca2e-c41f-11e5-9702-741f11cf3bcb.png)

**Comment by mrueschman** [comment]
Directly from MOP, won't correct at this point. Closing issue.
